version: '3'

services:
  tacotruck.product:
    image: tacotruck.product
    build:
      context: ./TacoTruck.Product
      dockerfile: Dockerfile

  tacotruck.customer:
    image: tacotruck.customer
    build:
      context: ./TacoTruck.Customer
      dockerfile: Dockerfile

  tacotruck.web:
    image: taco_truck_web:test
    ports:
      - "4200:4200"